#!/usr/bin/env bash

function not_exists() {
    test ! -x `command -v "$1"`
}

function step() {
  local banner='=============================='
  local banner_len=${#banner}
  local text="$1"
  local text_len=${#text}
  local padding="$(printf '%0.1s' ' '{1..500})"
  printf '\n%s\n' "$banner"
  printf '%*.*s%s%*.*s\n' \
    0 "$(((banner_len-text_len)/2))" "$padding" \
    "$text" \
    0 "$(((banner_len-text_len)/2))" "$padding"
  printf '%s\n' "$banner"
}

step 'INSTALLING BREW'
if not_exists brew; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else echo "brew is already installed"; fi

step 'INSTALLING GPG'
if not_exists gpg; then
  brew install gpg2
else echo "gpg is already installed"; fi

step 'INSTALLING GIT'
if not_exists git; then
  brew install git
else echo "git is already installed"; fi
